### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by magantisurya** [PacktPublishing/Spring-Boot-2.0-Projects#4]
Hi, There are some compile time errors w.r.t Article model. Article setters and getters are not working in any other classes. Please check once.

**Comment by shazin** [comment]
Hi @magantisurya Thanks for your reply. The Source Code uses Lombok to generate Getters, Setters, Equals etc. If you opening the source in am IDE install Lombok Plugin for that IDE or user **mvn clean install** to build.

**Comment by magantisurya** [comment]
Hi Shazin, I have used mvn clean install only but couldn't able to run blog project. Please fix the issues and push the code to git.

**Comment by shazin** [comment]
@magantisurya As I said the code uses Lombok. There is nothing wrong with the code. After building the code with mvn clean install you can use mvn spring-boot:run as these are Spring Boot Applications. This source code is associated with the book Spring Boot 2.0 Projects available at https://www.amazon.com/dp/B07CSLQ2M8/ref=cm_sw_r_cp_ep_dp_b6nKBbADS90FP. All instructions are available in the book.

**Comment by magantisurya** [comment]
Sir, please check once, the code is not running.

**Comment by magantisurya** [comment]
Please find the error stack for Spring boot blog project:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-10-19 19:40:30.211 ERROR 7088 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:771) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at com.packtpub.springboot2blog.SpringBoot2BlogApplication.main(SpringBoot2BlogApplication.java:29) [classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.0.RELEASE.jar:2.0.0.RELEASE]
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{bG7RY1kXQsSnQqoKM0yU7Q}{localhost}{127.0.0.1:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.doScroll(ElasticsearchTemplate.java:776) ~[spring-data-elasticsearch-3.0.5.RELEASE.jar:3.0.5.RELEASE]
        at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.startScroll(ElasticsearchTemplate.java:790) ~[spring-data-elasticsearch-3.0.5.RELEASE.jar:3.0.5.RELEASE]
        at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.delete(ElasticsearchTemplate.java:690) ~[spring-data-elasticsearch-3.0.5.RELEASE.jar:3.0.5.RELEASE]
        at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.deleteAll(AbstractElasticsearchRepository.java:256) ~[spring-data-elasticsearch-3.0.5.RELEASE.jar:3.0.5.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.0.5.RELEASE.jar:2.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.0.4.RELEASE.jar:5.0.4.RELEASE]
        at com.sun.proxy.$Proxy68.deleteAll(Unknown Source) ~[na:na]
        at com.packtpub.springboot2blog.service.UserService.deleteAll(UserService.java:41) ~[classes/:na]
        at com.packtpub.springboot2blog.config.SecurityConfig.lambda$applicationRunner$0(SecurityConfig.java:77) ~[classes/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:781) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        ... 10 common frames omitted

2018-10-19 19:40:30.227  INFO 7088 --- [  restartedMain] onfigReactiveWebServerApplicationContext : Closing org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@6456aae3: startup date [Fri Oct 19 19:40:11 CDT 2018]; root of context hierarchy
2018-10-19 19:40:30.243  INFO 7088 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-10-19 19:40:31.291  INFO 7088 --- [  restartedMain] r.ipc.netty.tcp.BlockingNettyContext     : Stopped HttpServer on /0.0.0.0:8080

**Comment by magantisurya** [comment]
I am getting one more error in Spring twittter project:
C:\workspaces\Spring-Boot-2.0-Projects\Chapter07\spring-boot-2-twitter-clone>mvn spring-boot:run
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] spring-boot-2-twitter-clone                                        [pom]
[INFO] backend                                                            [jar]
[INFO]
[INFO] --------------< com.packtpub:spring-boot-2-twitter-clone >--------------
[INFO] Building spring-boot-2-twitter-clone 0.0.1-SNAPSHOT                [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.0.2.RELEASE:run (default-cli) > test-compile @ spring-boot-2-twitter-clone >>>
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.0.2.RELEASE:run (default-cli) < test-compile @ spring-boot-2-twitter-clone <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.0.2.RELEASE:run (default-cli) @ spring-boot-2-twitter-clone ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] spring-boot-2-twitter-clone 0.0.1-SNAPSHOT ......... FAILURE [  2.243 s]
[INFO] backend 0.0.1-SNAPSHOT ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.115 s
[INFO] Finished at: 2018-10-19T19:58:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.2.RELEASE:run (default-cli) on project spring-boot-2-twitter-clone: Unable to find a suitable main class, please add a 'mainClass' property -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

C:\workspaces\Spring-Boot-2.0-Projects\Chapter07\spring-boot-2-twitter-clone>

**Comment by shazin** [comment]
You need to start the elasticsearch server. All the instructions are available in the book.
